dist: trusty
language: node_js

node_js:
  - 'lts/*'
  - '9'

cache:
  directories:
    - node_modules
  yarn: true


before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --v1.7.0
- export PATH="$HOME/.yarn/bin:$PATH"

sudo: false

script:
  - "yarn lint"
  - "yarn build"
